/**
 * Format a number as Australian currency
 * @param {number} amount - Amount in dollars
 * @returns {string} Formatted currency string
 */
function formatCurrency(amount) {
  return new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
  }).format(amount);
}

/**
 * Generate a plain text expense report
 * @param {Object} groups - Categorised expense groups
 * @param {string|undefined} month - Month filter applied
 * @param {number} total - Grand total
 * @returns {string} Formatted text report
 */
function generateTextReport(groups, month, total) {
  const lines = [];
  const divider = "━".repeat(50);

  lines.push(divider);
  lines.push("📊 EXPENSE REPORT");
  lines.push(`   Period: ${month || "All time"}`);
  lines.push(`   Generated: ${new Date().toLocaleDateString("en-AU")}`);
  lines.push(divider);
  lines.push("");

  for (const [category, data] of Object.entries(groups).sort(
    (a, b) => b[1].total - a[1].total,
  )) {
    const pct = ((data.total / total) * 100).toFixed(1);
    lines.push(`📁 ${category} — ${formatCurrency(data.total)} (${pct}%)`);

    for (const exp of data.expenses) {
      const date = new Date(exp.date).toLocaleDateString("en-AU");
      lines.push(
        `   ${date}  ${formatCurrency(exp.amount).padStart(12)}  ${exp.description}  [${exp.employee}]`,
      );
    }
    lines.push("");
  }

  lines.push(divider);
  lines.push(`💰 GRAND TOTAL: ${formatCurrency(total)}`);
  lines.push(divider);
  lines.push("");
  lines.push("Generated by FinanceBot — Digital Department");

  return lines.join("\n");
}

/**
 * Generate an HTML expense report
 * @param {Object} groups - Categorised expense groups
 * @param {string|undefined} month - Month filter applied
 * @param {number} total - Grand total
 * @returns {string} HTML report string
 */
function generateHTMLReport(groups, month, total) {
  const rows = Object.entries(groups)
    .sort((a, b) => b[1].total - a[1].total)
    .map(
      ([cat, data]) => `
    <tr class="category-row">
      <td colspan="4"><strong>${cat}</strong> — ${formatCurrency(data.total)} (${((data.total / total) * 100).toFixed(1)}%)</td>
    </tr>
    ${data.expenses
      .map(
        (e) => `
    <tr>
      <td>${new Date(e.date).toLocaleDateString("en-AU")}</td>
      <td>${e.description}</td>
      <td>${e.employee}</td>
      <td class="amount">${formatCurrency(e.amount)}</td>
    </tr>`,
      )
      .join("")}`,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Expense Report — ${month || "All Time"}</title>
  <style>
    body { font-family: -apple-system, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #1a1a2e; }
    h1 { color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 0.5rem; }
    table { width: 100%; border-collapse: collapse; margin: 1.5rem 0; }
    th { background: #0f3460; color: white; padding: 0.75rem; text-align: left; }
    td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #e0e0e0; }
    .category-row { background: #f0f4ff; }
    .amount { text-align: right; font-variant-numeric: tabular-nums; }
    .total { font-size: 1.5rem; font-weight: bold; color: #0f3460; margin: 1rem 0; }
    .footer { color: #888; font-size: 0.85rem; margin-top: 2rem; border-top: 1px solid #e0e0e0; padding-top: 0.5rem; }
  </style>
</head>
<body>
  <h1>📊 Expense Report</h1>
  <p>Period: <strong>${month || "All time"}</strong> | Generated: ${new Date().toLocaleDateString("en-AU")}</p>
  <table>
    <thead><tr><th>Date</th><th>Description</th><th>Employee</th><th>Amount</th></tr></thead>
    <tbody>${rows}
      <tr style="border-top: 3px solid #0f3460;">
        <td colspan="3"><strong>GRAND TOTAL</strong></td>
        <td class="amount"><strong>${formatCurrency(total)}</strong></td>
      </tr>
    </tbody>
  </table>
  <div class="footer">Generated by FinanceBot — Digital Department</div>
</body>
</html>`;
}

/**
 * Generate a JSON expense report
 * @param {Object} groups - Categorised expense groups
 * @param {string|undefined} month - Month filter applied
 * @param {number} total - Grand total
 * @returns {string} JSON string
 */
function generateJSONReport(groups, month, total) {
  return JSON.stringify(
    {
      period: month || "all",
      generatedAt: new Date().toISOString(),
      grandTotal: total,
      categories: Object.fromEntries(
        Object.entries(groups).map(([cat, data]) => [
          cat,
          {
            total: data.total,
            count: data.count,
            expenses: data.expenses,
          },
        ]),
      ),
    },
    null,
    2,
  );
}

module.exports = {
  generateTextReport,
  generateHTMLReport,
  generateJSONReport,
  formatCurrency,
};
